### ISSUE TITLE
SNOW-162410: TypeError: winston.createLogger is not a constructor

### ISSUE THREAD

**Issue by Karthickvasu** [snowflakedb/snowflake-connector-nodejs#106]
We are facing following error in our application

TypeError: winston.createLogger is not a constructor
    at logMessage (/var/www/app-name/node_modules/snowflake-sdk/lib/logger/node.js:39:23)
    at log (/var/www/app-name/node_modules/snowflake-sdk/lib/logger/core.js:312:7)
    at Object.info (/var/www/app-name/node_modules/snowflake-sdk/lib/logger/core.js:213:9)
    at Logger.info (/var/www/app-name/node_modules/snowflake-sdk/lib/logger/node.js:116:17)
    at canEarlyExitForOCSP (/var/www/app-name/node_modules/snowflake-sdk/lib/agent/socket_util.js:174:30)
    at /var/www/app-name/node_modules/snowflake-sdk/lib/agent/socket_util.js:243:28
    at /var/www/app-name/node_modules/snowflake-sdk/lib/agent/socket_util.js:329:11
    at Object.dynatraceOnServiceExecutionIndicator (/opt/dynatrace/oneagent/agent/res/nodeagent/nodejsagent.js:1764:20)
    at Object.b.safeInvoke (/opt/dynatrace/oneagent/agent/res/nodeagent/nodejsagent.js:1817:29)
    at /opt/dynatrace/oneagent/agent/res/nodeagent/nodejsagent.js:3166:21
    at process._tickCallback (internal/process/next_tick.js:61:11)

Node version: 10.20.1
NPM version: 6.14.4

OS: CENTOS - Version 7

snowflake-sdk-1.5.1

snowflake connection establish code

public async connect() {
        this.snowflake = Snowflake.createConnection(
            { ...this.dbInfo, clientSessionKeepAlive: true, clientSessionKeepAliveHeartbeatFrequency: 3600 },
            { logSql: console.log }
        );

        this.snowflake.connect((err, conn) => {
            if (err) {
                Logger.error('Snowflake', `Unable to connect: ${JSON.stringify(err)}`);
            }
            else {
                Logger.info('Snowflake', `Successfully connected to Snowflake - ${conn.getId()}`);
            }
        }
        );
    }

**Comment by Hiraji** [comment]
I am facing the same issue, @Karthickvasu did you find any solution on this

**Comment by sfc-gh-dszmolka** [comment]
sorry to see this issue was unanswered for such a long time. however, i didn't encounter it in the more recent driver versions.
if you're still seeing it with the more recent driver versions too, can you please reopen the issue and post a reproduction scenario and perhaps even a code snippet so we could look into it ? thank you in advance!

**Comment by thangaduraicse** [comment]
I believe the error is due to this code.
https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/lib/logger/node.js#L105

winston.createLogger is not a constructor. Hence, we need to remove the 'new' keyword. Correct me If I am wrong?
