### ISSUE TITLE
SNOW-363929: issues connecting with node snowflake-sdk, asn1

### ISSUE THREAD

**Issue by shoma-ftv** [snowflakedb/snowflake-connector-nodejs#171]
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?
node v10.12.0
npm 6.4.1

2. What operating system and processor architecture are you using?
Mac:
System Version: macOS 10.14.6 (18G6020)
      Kernel Version: Darwin 18.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Coretelligent’s MacBook Pro
      User Name: Shoma Nishikawa (shoma)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Disabled
      Time since boot: 3 days 9:14

3. What are the component versions in the environment (`npm list`)?
snowflake-sdk@1.6.1

4. What did you do?
Standard snowflake-sdk example with node

5. What did you expect to see?
successful call to snowflake instance

6. What did you see instead?
errors in logs

Trying to set up a node/express endpoint that can hit my snowflake instance.

I've done the following, which works in a bare-bones node file, but breaks when put into my app:

```
import snowflake from 'snowflake-sdk';

const connection = snowflake.createConnection({
      account: 'ACCOUNT',
      username: 'USER',
      password: 'PW'
  });

  let connection_ID;

  connection.connect(function(err, conn) {
    if (err) {
      console.error('Unable to connect: ' + err.message);
    } else {
      console.log('Successfully connected to Snowflake.');
      // Optional: store the connection ID.
      connection_ID = conn.getId();
      var statement = connection.execute({
        sqlText: 'SELECT V:city FROM "SNOWFLAKE_SAMPLE_DATA"."WEATHER"."DAILY_14_TOTAL" LIMIT 10',
        complete: function(err, stmt, rows) {
          if (err) {
            console.error('Failed to execute statement due to the following error: ' + err.message);
          } else {
            console.log('Successfully executed statement: ' + stmt.getSqlText());
            console.log(rows);
          }
        }
      });
    }
  });
```

This results in the following errors:

```
{
    "error": {
        "path": "",
        "message": "Unsupported type: object at: (shallow)"
    },
    "level": "error",
    "message": "uncaughtException: Unsupported type: object at: (shallow)\nError: Unsupported type: object at: (shallow)\n    at Reporter.error (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/reporter.js:76:11)\n    at new EncoderBuffer (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/buffer.js:86:21)\n    at EncoderBuffer.<anonymous> (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/buffer.js:70:16)\n    at Array.map (<anonymous>)\n    at new EncoderBuffer (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/buffer.js:68:24)\n    at DERNode.createEncoderBuffer [as _createEncoderBuffer] (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/node.js:477:10)\n    at DERNode.encode [as _encodeValue] (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/node.js:545:20)\n    at DERNode.encode [as _encode] (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/node.js:485:21)\n    at DERNode.encode [as _encodeValue] (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/node.js:500:30)\n    at DERNode.encode [as _encode] (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/node.js:485:21)\n    at CertID.encode (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/encoders/der.js:22:20)\n    at Entity.encode (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/api.js:60:32)\n    at Object.exports.buildCertId (/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/cert_util.js:83:36)\n    at OcspResponseCache.get (/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/ocsp_response_cache.js:169:29)\n    at getOcspResonseAndVerify (/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/socket_util.js:314:45)\n    at validateCert (/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/socket_util.js:358:3)\n    at eachCallback (/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/socket_util.js:220:5)\n    at validateCertChain (/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/socket_util.js:253:5)\n    at TLSSocket.validate (/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/socket_util.js:88:7)\n    at TLSSocket.emit (events.js:187:15)\n    at TLSSocket.EventEmitter.emit (domain.js:442:20)\n    at TLSSocket._finishInit (_tls_wrap.js:631:8)",
    "stack": "Error: Unsupported type: object at: (shallow)\n    at Reporter.error (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/reporter.js:76:11)\n    at new EncoderBuffer (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/buffer.js:86:21)\n    at EncoderBuffer.<anonymous> (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/buffer.js:70:16)\n    at Array.map (<anonymous>)\n    at new EncoderBuffer (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/buffer.js:68:24)\n    at DERNode.createEncoderBuffer [as _createEncoderBuffer] (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/node.js:477:10)\n    at DERNode.encode [as _encodeValue] (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/node.js:545:20)\n    at DERNode.encode [as _encode] (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/node.js:485:21)\n    at DERNode.encode [as _encodeValue] (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/node.js:500:30)\n    at DERNode.encode [as _encode] (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/node.js:485:21)\n    at CertID.encode (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/encoders/der.js:22:20)\n    at Entity.encode (/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/api.js:60:32)\n    at Object.exports.buildCertId (/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/cert_util.js:83:36)\n    at OcspResponseCache.get (/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/ocsp_response_cache.js:169:29)\n    at getOcspResonseAndVerify (/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/socket_util.js:314:45)\n    at validateCert (/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/socket_util.js:358:3)\n    at eachCallback (/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/socket_util.js:220:5)\n    at validateCertChain (/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/socket_util.js:253:5)\n    at TLSSocket.validate (/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/socket_util.js:88:7)\n    at TLSSocket.emit (events.js:187:15)\n    at TLSSocket.EventEmitter.emit (domain.js:442:20)\n    at TLSSocket._finishInit (_tls_wrap.js:631:8)",
    "exception": true,
    "date": "Wed Jun 02 2021 19:20:07 GMT-0400 (Eastern Daylight Time)",
    "process": {
        "pid": 3675,
        "uid": 503,
        "gid": 20,
        "cwd": "/Users/test/code/myApp",
        "execPath": "/Users/test/.nvm/versions/node/v10.12.0/bin/node",
        "version": "v10.12.0",
        "argv": ["node", "/Users/test/code/myApp/src/worker-server/index.js"],
        "memoryUsage": {
            "rss": 154824704,
            "heapTotal": 143810560,
            "heapUsed": 102881480,
            "external": 21753537
        }
    },
    "os": {
        "loadavg": [6.28125, 11.08203125, 11.08056640625],
        "uptime": 291134
    },
    "trace": [{
        "column": 11,
        "file": "/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/reporter.js",
        "function": "Reporter.error",
        "line": 76,
        "method": "error",
        "native": false
    }, {
        "column": 21,
        "file": "/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/buffer.js",
        "function": "new EncoderBuffer",
        "line": 86,
        "method": null,
        "native": false
    }, {
        "column": 16,
        "file": "/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/buffer.js",
        "function": null,
        "line": 70,
        "method": null,
        "native": false
    }, {
        "column": null,
        "file": null,
        "function": "Array.map",
        "line": null,
        "method": "map",
        "native": false
    }, {
        "column": 24,
        "file": "/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/buffer.js",
        "function": "new EncoderBuffer",
        "line": 68,
        "method": null,
        "native": false
    }, {
        "column": 10,
        "file": "/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/node.js",
        "function": "DERNode.createEncoderBuffer [as _createEncoderBuffer]",
        "line": 477,
        "method": "createEncoderBuffer [as _createEncoderBuffer]",
        "native": false
    }, {
        "column": 20,
        "file": "/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/node.js",
        "function": "DERNode.encode [as _encodeValue]",
        "line": 545,
        "method": "encode [as _encodeValue]",
        "native": false
    }, {
        "column": 21,
        "file": "/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/node.js",
        "function": "DERNode.encode [as _encode]",
        "line": 485,
        "method": "encode [as _encode]",
        "native": false
    }, {
        "column": 30,
        "file": "/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/node.js",
        "function": "DERNode.encode [as _encodeValue]",
        "line": 500,
        "method": "encode [as _encodeValue]",
        "native": false
    }, {
        "column": 21,
        "file": "/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/base/node.js",
        "function": "DERNode.encode [as _encode]",
        "line": 485,
        "method": "encode [as _encode]",
        "native": false
    }, {
        "column": 20,
        "file": "/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/encoders/der.js",
        "function": "CertID.encode",
        "line": 22,
        "method": "encode",
        "native": false
    }, {
        "column": 32,
        "file": "/Users/test/code/myApp/node_modules/asn1.js/lib/asn1/api.js",
        "function": "Entity.encode",
        "line": 60,
        "method": "encode",
        "native": false
    }, {
        "column": 36,
        "file": "/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/cert_util.js",
        "function": "Object.exports.buildCertId",
        "line": 83,
        "method": "buildCertId",
        "native": false
    }, {
        "column": 29,
        "file": "/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/ocsp_response_cache.js",
        "function": "OcspResponseCache.get",
        "line": 169,
        "method": "get",
        "native": false
    }, {
        "column": 45,
        "file": "/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/socket_util.js",
        "function": "getOcspResonseAndVerify",
        "line": 314,
        "method": null,
        "native": false
    }, {
        "column": 3,
        "file": "/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/socket_util.js",
        "function": "validateCert",
        "line": 358,
        "method": null,
        "native": false
    }, {
        "column": 5,
        "file": "/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/socket_util.js",
        "function": "eachCallback",
        "line": 220,
        "method": null,
        "native": false
    }, {
        "column": 5,
        "file": "/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/socket_util.js",
        "function": "validateCertChain",
        "line": 253,
        "method": null,
        "native": false
    }, {
        "column": 7,
        "file": "/Users/test/code/myApp/node_modules/snowflake-sdk/lib/agent/socket_util.js",
        "function": "TLSSocket.validate",
        "line": 88,
        "method": "validate",
        "native": false
    }, {
        "column": 15,
        "file": "events.js",
        "function": "TLSSocket.emit",
        "line": 187,
        "method": "emit",
        "native": false
    }, {
        "column": 20,
        "file": "domain.js",
        "function": "TLSSocket.EventEmitter.emit",
        "line": 442,
        "method": "emit",
        "native": false
    }, {
        "column": 8,
        "file": "_tls_wrap.js",
        "function": "TLSSocket._finishInit",
        "line": 631,
        "method": "_finishInit",
        "native": false
    }]
}
```

What's most strange about this is if I reload the page a bunch, it eventually works. However, it's totally unreliable.

I've tried all the solutions here, to no avail, including installing asn1 directly and adding to package.json resolutions:
https://github.com/snowflakedb/snowflake-connector-nodejs/issues/16

**Comment by vladarsky** [comment]
I have the same issue

**Comment by james-bowers** [comment]
I'm finding this too @vladarsky and @shoma-ftv . Did you find a fix?
