### ISSUE TITLE
Bulk Insert: Unsupported data type 'VARIANT'

### ISSUE THREAD

**Issue by mwillbanks** [snowflakedb/snowflake-connector-nodejs#237]
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?
node: v16.13.0
npm: 8.1.0

2. What operating system and processor architecture are you using?

Linux:
    Lambda
Mac:
      System Version: macOS 12.0.1 (21A559)
      Kernel Version: Darwin 21.1.0

3. What are the component versions in the environment (`npm list`)?
1.6.5

4. What did you do?
Basically exactly what the example showed for bulk inserting:

```
connection.execute({
  sqlText: 'insert into t(c1, c2, c3) values(?, ?, ?)',
  binds: [[1, 'string1', 2.0], [2, 'string2', 4.0], [3, 'string3', 6.0]]
});
```

5. What did you expect to see?

A successful insert.

6. What did you see instead?

A variant error, see information below.

7. Add this to get standard output.
 
Note, sensitive data has been replaced with X's.

```
{"level":"DEBUG","message":"[11:35:51.3551 AM]: Contacting SF: /session/v1/login-request?requestId=XXXX&warehouse=XXXX&databaseName=XXXX&schemaName=XXXXXXX, (1/5)"}
{"level":"TRACE","message":"[11:35:51.3551 AM]: https://XXXXXXX.us-east-1.snowflakecomputing.com/session/v1/login-request?requestId=XXXX&warehouse=XXXX&databaseName=XXXX&schemaName=XXXXXXX"}
{"level":"DEBUG","message":"[11:35:51.3551 AM]: Reading OCSP cache file. /XXXX/Library/Caches/Snowflake/ocsp_response_cache.json"}
{"level":"TRACE","message":"[11:35:51.3551 AM]: Returning OCSP status for certificate 07670B83EA6BF8BA8687E01312EF8EB4 from cache"}
{"level":"TRACE","message":"[11:35:51.3551 AM]: socket reused = false"}
{"level":"TRACE","message":"[11:35:51.3551 AM]: Contact OCSP Cache Server: http://ocsp.snowflakecomputing.com/ocsp_response_cache.json"}
{"level":"DEBUG","message":"[11:35:51.3551 AM]: Finish OCSP Cache Server: http://ocsp.snowflakecomputing.com/ocsp_response_cache.json"}
{"level":"DEBUG","message":"[11:35:51.3551 AM]: ReporterError: Unsupported type: object at: (shallow)\n    at Reporter.error (/Volumes/Projects/XXXXXXX/node_modules/ocsp/node_modules/asn1.js/lib/asn1/base/reporter.js:76:11)\n    at new EncoderBuffer (/Volumes/Projects/XXXXXXX/node_modules/ocsp/node_modules/asn1.js/lib/asn1/base/buffer.js:86:21)\n    at EncoderBuffer.<anonymous> (/Volumes/Projects/XXXXXXX/node_modules/ocsp/node_modules/asn1.js/lib/asn1/base/buffer.js:70:16)\n    at Array.map (<anonymous>)\n    at new EncoderBuf"}
{"level":"DEBUG","message":"[11:35:51.3551 AM]: ReporterError: Unsupported type: object at: (shallow)\n    at Reporter.error (/Volumes/Projects/XXXXXXX/node_modules/ocsp/node_modules/asn1.js/lib/asn1/base/reporter.js:76:11)\n    at new EncoderBuffer (/Volumes/Projects/XXXXXXX/node_modules/ocsp/node_modules/asn1.js/lib/asn1/base/buffer.js:86:21)\n    at EncoderBuffer.<anonymous> (/Volumes/Projects/XXXXXXX/node_modules/ocsp/node_modules/asn1.js/lib/asn1/base/buffer.js:70:16)\n    at Array.map (<anonymous>)\n    at new EncoderBuf"}
{"level":"DEBUG","message":"[11:35:51.3551 AM]: ReporterError: Unsupported type: object at: (shallow)\n    at Reporter.error (/Volumes/Projects/XXXXXXX/node_modules/ocsp/node_modules/asn1.js/lib/asn1/base/reporter.js:76:11)\n    at new EncoderBuffer (/Volumes/Projects/XXXXXXX/node_modules/ocsp/node_modules/asn1.js/lib/asn1/base/buffer.js:86:21)\n    at EncoderBuffer.<anonymous> (/Volumes/Projects/XXXXXXX/node_modules/ocsp/node_modules/asn1.js/lib/asn1/base/buffer.js:70:16)\n    at Array.map (<anonymous>)\n    at new EncoderBuf"}
{"level":"INFO","message":"[11:35:51.3551 AM]: WARNING!!! using fail-open to connect. Driver is connecting to an HTTPS endpoint without OCSP based Certificated Revocation checking as it could not obtain a valid OCSP Response to use from the CA OCSP responder. Details:"}
{"level":"DEBUG","message":"[11:35:51.3551 AM]: /XXXX/Library/Caches/Snowflake/ocsp_response_cache.json"}
{"level":"DEBUG","message":"[11:35:51.3551 AM]: Writing OCSP cache file. /XXXX/Library/Caches/Snowflake/ocsp_response_cache.json"}
{"level":"TRACE","message":"[11:35:51.3551 AM]: OCSP validation succeeded for XXXXXXX.us-east-1.snowflakecomputing.com"}
{"level":"TRACE","message":"[11:35:52.3552 AM]: https://XXXXXXX.us-east-1.snowflakecomputing.com/queries/v1/query-request?requestId=a6a8c47a-2e23-41bd-b5b8-9692d351bddf"}
Executed: INSERT INTO XXXXXX (XXXXXX, XXXXXX, XXXXXX, XXXXXX, XXXXXX, XXXXXX, XXXXXX, XXXXXX, XXXXXX, XXXXXX, XXXXXX, XXXXXX, XXXXXX, XXXXXX, XXXXXX, XXXXXX, XXXXXX, XXXXXX, XXXXXX, XXXXXX) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);  with binds: [[["XXXXXX","2021-12-01T22:16:55","XXXXXX","XXXXXX",12239,57,8,8133,144,374,2,41,0,2,0,15,1,0,0,"2021-12-02T17:35:51.266Z"]]];  Elapsed time: 66ms
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error [OperationFailedError]: SQL compilation error:
Unsupported data type 'VARIANT'.
    at createError (/Volumes/Projects/XXXXXXX/node_modules/snowflake-sdk/lib/errors.js:535:15)
    at Object.exports.createOperationFailedError (/Volumes/Projects/XXXXXXX/node_modules/snowflake-sdk/lib/errors.js:314:10)
    at Object.callback (/Volumes/Projects/XXXXXXX/node_modules/snowflake-sdk/lib/services/sf.js:643:28)
    at Request.<anonymous> (/Volumes/Projects/XXXXXXX/node_modules/snowflake-sdk/lib/http/base.js:107:25)
    at Request._callback (/Volumes/Projects/XXXXXXX/node_modules/lodash/lodash.js:10118:25)
    at Request.requestRetryReply [as reply] (/Volumes/Projects/XXXXXXX/node_modules/requestretry/index.js:114:19)
    at Request.<anonymous> (/Volumes/Projects/XXXXXXX/node_modules/requestretry/index.js:155:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: '002040',
  sqlState: '42601',
  data: {
    internalError: false,
    errorCode: '002040',
    age: 0,
    sqlState: '42601',
    queryId: 'XXXXXX',
    line: -1,
    pos: -1,
    type: 'COMPILATION'
  }
}
```

**Comment by mwillbanks** [comment]
I see what I did there, I have too many nested arrays 😢
