### ISSUE TITLE
SNOW-541891: Keepalive heartbeat not working

### ISSUE THREAD

**Issue by JamieSinn** [snowflakedb/snowflake-connector-nodejs#261]
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?
16.13.0 and 
8.10.0
2. What operating system and processor architecture are you using?
Any

3. What are the component versions in the environment (`npm list`)?

4. What did you do?
Let a connection fail after 5 hours while having the `clientSessionKeepAlive` config value enabled.

5. What did you expect to see?

Heartbeat requests to snowflake, to keep the session alive. None were made. 
Checked via the following query:

```
select * from table(information_schema.query_history_by_user('USER',dateadd('hours',-4,current_timestamp()),current_timestamp())) where query_text like 'select%1';
```

6. What did you see instead?
Connection is not kept alive- and is closing after 5 hours.

```
ClientError: Unable to perform operation using terminated connection.
    at createError (/src/node_modules/snowflake-sdk/lib/errors.js:535:15)
    at Object.exports.createClientError (/src/node_modules/snowflake-sdk/lib/errors.js:350:10)
    at /src/node_modules/snowflake-sdk/lib/services/sf.js:1520:21
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

7. Add this to get standard output.
 
```
var snowflake = require('./snowflake');
snowflake.configure(
{
  logLevel: 'trace'
});
```

I don't see where (at all) the heartbeat is implemented to keep the session alive. The docs: https://docs.snowflake.com/en/user-guide/nodejs-driver-use.html#additional-connection-options state that this is supposed to send a query (`select 1`) to snowflake to keep it alive - but after checking the snowflake query logs via the above query - nothing was returned remotely related. This, plus the error above leads me to believe that it is not properly implemented.

**Comment by JamieSinn** [comment]
Attached to case id 00315191.

**Comment by sfc-gh-kwagner** [comment]
@JamieSinn is that case id number a Snowflake support case id?

**Comment by JamieSinn** [comment]
Yep.

**Comment by sfc-gh-kwagner** [comment]
@SimbaGithub can you look into this bug?

**Comment by sfc-gh-dszmolka** [comment]
checked above Support case id and it seems to be closed . also during the past days i experimented quite a bit around the keepalive (`clientSessionKeepAlive` as a connection config) and i can say it is working - at least now with 1.6.17 for sure.

i'm closing this old issue for now, but if you still running into any keepalive related issues, please feel free to reopen it and we'll debug further.
