### ISSUE TITLE
SNOW-592825: use UDFs SQL does not working

### ISSUE THREAD

**Issue by Takaichi00** [snowflakedb/snowflake-connector-nodejs#305]
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?
```
$ node --version
v16.15.0

$ npm --version
8.5.5
```

2. What operating system and processor architecture are you using?
Mac:
    macOS Monterey, Intel

3. What are the component versions in the environment (`npm list`)?
* `snowflake-sdk@1.6.9`
* `@types/snowflake-sdk@1.6.4`

4. What did you do?

Query_MYSQL is UDFs (User-Defined Functions).
When execute `SHOW user functions;`, then return bellow.
```
SHOW user functions;

Row | created_on          | name        | ...
1   | 2022-03-31 18:57:09 | QUERY_MYSQL | ...

```

And when execute UDFs SQL by snowflake blowser execution environment, the SQL is success.

```
SELECT * FROM TABLE(QUERY_MYSQL('column_a','column_b','select id, name from mysql_table'));
```

But when I execute the SQL node.js driver, then occurred `SQL compilation error:`

* Source Code with execute UDFs SQL
```
snowConnection.execute({
    return new Promise<void>((resolve, reject) => {
        sqlText: `
                SELECT * FROM TABLE(QUERY_MYSQL('column_a','column_b','select id, name from mysql_table'));
                    `,
        complete: function (err, stmt) {
            if (err) {
                console.error("Failed to execute statement due to the following error: " + err.message);
                reject(err);
            } else {
                console.log("Successfully executed statement: " + stmt.getSqlText());
                resolve();
            }
        }});
    });
```

* Error
```
-- start executeSqlToSnowflake --
Failed to execute statement due to the following error: SQL compilation error:
Unknown table function QUERY_MYSQL
/Users/xxxx/typescript-project/node_modules/snowflake-sdk/lib/errors.js:535
  var error = new Error();
              ^
Error [OperationFailedError]: SQL compilation error:
Unknown table function QUERY_MYSQL
    at createError (/Users/xxxx/typescript-project/node_modules/snowflake-sdk/lib/errors.js:535:15)
    at Object.exports.createOperationFailedError (/Users/xxxx/typescript-project/node_modules/snowflake-sdk/lib/errors.js:314:10)
    at Object.callback (/Users/xxxx/typescript-project/node_modules/snowflake-sdk/lib/services/sf.js:643:28)
    at Request.<anonymous> (/Users/xxxx/typescript-project/node_modules/snowflake-sdk/lib/http/base.js:107:25)
    at Request._callback (/Users/xxxx/typescript-project/node_modules/lodash/lodash.js:10118:25)
    at Request.requestRetryReply [as reply] (/Users/xxxx/typescript-project/node_modules/requestretry/index.js:151:19)
    at Request.<anonymous> (/Users/xxxx/typescript-project/node_modules/requestretry/index.js:192:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: '002142',
  sqlState: '42601',
  data: {
    internalError: false,
    errorCode: '002142',
    age: 0,
    sqlState: '42601',
    queryId: '01a461f9-0000-5f73-0000-67f1002cf166',
    line: -1,
    pos: -1,
    type: 'COMPILATION'
  }
}

Process finished with exit code 1
```

5. What did you expect to see?
Success use UDFs SQL Query.

6. What did you see instead?
Above Error (4. What did you do?)

7. Add this to get standard output.
Done. 

```
var snowflake = require('./snowflake');
snowflake.configure(
{
  logLevel: 'trace'
});
```

**Comment by Takaichi00** [comment]
I have confirmed that there is a test for `create or replace function add1 (n number)` but no test for use `add1` sql in the system test.
https://github.com/snowflakedb/snowflake-connector-nodejs/blob/699ccbb90a10fc58a58d2405cb20926b94c5210f/system_test/testSystemGetObjects.js#L33

**Comment by Takaichi00** [comment]
I checked the history in Snowflake and confirmed that the query was executed correctly.

I checked the code and found that I did not specify the Schema setting for "createConnection".
By setting the Schema, I was able to execute the query using UDFs.

I would appreciate if you could specify the schema in your sample code if you don't mind.
https://docs.snowflake.com/ja/user-guide/nodejs-driver-use.html

Thanks.
