### ISSUE TITLE
SNOW-611837: File PUT errors - testPutGet integration test fails

### ISSUE THREAD

**Issue by vagayan** [snowflakedb/snowflake-connector-nodejs#316]
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?
Node v16.13.0, NPM 8.1.3
2. What operating system and processor architecture are you using?

Mac:
System Version: macOS 11.6 (20G165)
Kernel Version: Darwin 20.6.0

Note that this fails under Linux too.

3. What are the component versions in the environment (`npm list`)?
The only components are from this repo's package.json. The integration test for testPutGet.js is failing. 

4. What did you do?
Here are the full steps to reproduce:
1) Clone this repo and cd to it
git clone https://github.com/snowflakedb/snowflake-connector-nodejs.git
cd snowflake-connector-nodejs
2) Edit package.json to execute the testPutGet.js integration test
 "test": "mocha test/integration/testPutGet.js"
3) Export required env variables (substitute your values)
export SNOWFLAKE_TEST_USER=username
export SNOWFLAKE_TEST_PASSWORD=password
export SNOWFLAKE_TEST_ACCOUNT=account.locator
export SNOWFLAKE_TEST_WAREHOUSE=YOUR_WH
export SNOWFLAKE_TEST_DATABASE=YOUR_DB
export SNOWFLAKE_TEST_SCHEMA=YOUR_SCHEMA
export SNOWFLAKE_TEST_ROLE=YOUR_ROLE

5. What did you expect to see?6. 
Expected the test to succeed.

7. What did you see instead?
Instead tests are failing. This is occurring on multiple Snowflake Accounts, Enterprise and Business Critical with AWS as the cloud provider. All PUT GET tests are failing.

  1) PUT GET test
       bzip2:
      Uncaught AssertionError [ERR_ASSERTION]: {"name":"
OperationFailedError","code":"000603","message":"SQL execution internal
error:\nProcessing aborted due to error 300010:2264965618; incident
4335452.","sqlState":"XX000","data":{"internalError":false,"errorCode":"
000603","age":1,"sqlState":"XX000","queryId":null}}
      + expected - actual
-false +true
      at EventEmitter.executeOptions.complete (test/integration
/testUtil.js:37:12)
      at RowStream.<anonymous> (lib/connection/statement.js:625:19)
      at RowStream.emit (node:events:390:28)
      at RowStream.emit (node:domain:475:12)
      at emitError (lib/connection/result/row_stream.js:305:10)
      at close (lib/connection/result/row_stream.js:269:7)
      at init (lib/connection/result/row_stream.js:134:7)
      at processTicksAndRejections (node:internal/process/task_queues:
78:11)
  2) PUT GET test
       brotli:
      Uncaught AssertionError [ERR_ASSERTION]: {"name":"
OperationFailedError","code":"000603","message":"SQL execution internal
error:\nProcessing aborted due to error 300010:2264965618; incident
1430957.","sqlState":"XX000","data":{"internalError":false,"errorCode":"
000603","age":1,"sqlState":"XX000","queryId":null}}
      + expected - actual
-false +true
         at EventEmitter.executeOptions.complete (test/integration
/testUtil.js:37:12)
      at RowStream.<anonymous> (lib/connection/statement.js:625:19)
      at RowStream.emit (node:events:390:28)
      at RowStream.emit (node:domain:475:12)
      at emitError (lib/connection/result/row_stream.js:305:10)
      at close (lib/connection/result/row_stream.js:269:7)
      at init (lib/connection/result/row_stream.js:134:7)
      at processTicksAndRejections (node:internal/process/task_queues:
78:11)
  3) PUT GET test
       deflate:
      Uncaught AssertionError [ERR_ASSERTION]: {"name":"
OperationFailedError","code":"000603","message":"SQL execution internal
error:\nProcessing aborted due to error 300010:2264965618; incident
4489653.","sqlState":"XX000","data":{"internalError":false,"errorCode":"
000603","age":1,"sqlState":"XX000","queryId":null}}
      + expected - actual
-false +true
      at EventEmitter.executeOptions.complete (test/integration
/testUtil.js:37:12)
      at RowStream.<anonymous> (lib/connection/statement.js:625:19)
      at RowStream.emit (node:events:390:28)
      at RowStream.emit (node:domain:475:12)
      at emitError (lib/connection/result/row_stream.js:305:10)
      at close (lib/connection/result/row_stream.js:269:7)
      at init (lib/connection/result/row_stream.js:134:7)
      at processTicksAndRejections (node:internal/process/task_queues:
78:11)
  4) PUT GET test
       raw deflate:
      Uncaught AssertionError [ERR_ASSERTION]: {"name":"
OperationFailedError","code":"000603","message":"SQL execution internal
error:\nProcessing aborted due to error 300010:2264965618; incident
8157656.","sqlState":"XX000","data":{"internalError":false,"errorCode":"
000603","age":1,"sqlState":"XX000","queryId":null}}
      + expected - actual
-false +true
      at EventEmitter.executeOptions.complete (test/integration
/testUtil.js:37:12)

at RowStream.<anonymous> (lib/connection/statement.js:625:19)
      at RowStream.emit (node:events:390:28)
      at RowStream.emit (node:domain:475:12)
      at emitError (lib/connection/result/row_stream.js:305:10)
      at close (lib/connection/result/row_stream.js:269:7)
      at init (lib/connection/result/row_stream.js:134:7)
      at processTicksAndRejections (node:internal/process/task_queues:
78:11)
  5) PUT GET test
       zstd:
      Uncaught AssertionError [ERR_ASSERTION]: {"name":"
OperationFailedError","code":"000603","message":"SQL execution internal
error:\nProcessing aborted due to error 300010:2264965618; incident
9513934.","sqlState":"XX000","data":{"internalError":false,"errorCode":"
000603","age":1,"sqlState":"XX000","queryId":null}}
      + expected - actual
-false +true
      at EventEmitter.executeOptions.complete (test/integration
/testUtil.js:37:12)
      at RowStream.<anonymous> (lib/connection/statement.js:625:19)
      at RowStream.emit (node:events:390:28)
      at RowStream.emit (node:domain:475:12)
      at emitError (lib/connection/result/row_stream.js:305:10)
      at close (lib/connection/result/row_stream.js:269:7)
      at init (lib/connection/result/row_stream.js:134:7)
      at processTicksAndRejections (node:internal/process/task_queues:
78:11)

A case has been opened with Snowflake Support but have not seen any resolution for the last several months.

**Comment by vagayan** [comment]
To clarify, the actual error on the Snowflake side is with the "COPY INTO TEMP_TABLE" command that follows the PUT command.

**Comment by sfc-gh-dszmolka** [comment]
i know it's very late and possibly not necessarily that helpful, but the error pattern `Processing aborted due to error 300010:2264965618` does not look like a driver related issue. found traces of this issue in internal discussions and seems to be tied to some platform-internal issue. (internally tracked on ticket 570758)

since this issue does not seem to be specific to snowflake-sdk (or as a matter of fact, any other driver), i'm marking this issue in this repo as closed.
