### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'set') at OcspResponseCache.set

### ISSUE THREAD

**Issue by pavannarayan05** [snowflakedb/snowflake-connector-nodejs#349]
I am using node version v17.9.0. 
OS is Linux. 
I am using Kubernetes and launching a nodejs application to connect with snowflake and execute a query. 

version of snowflake-promise is 2.2.0.
version of snowflake-sdk is 1.6.14.

I am getting below error. Can you please suggest.

```
/app/node_modules/snowflake-sdk/lib/agent/ocsp_response_cache.js:157
    cache.set(certId, response);
          ^
TypeError: Cannot read properties of undefined (reading 'set')
    at OcspResponseCache.set (/app/node_modules/snowflake-sdk/lib/agent/ocsp_response_cache.js:157:11)
    at /app/node_modules/snowflake-sdk/lib/agent/socket_util.js:232:32
    at done (/app/node_modules/snowflake-sdk/lib/agent/check.js:142:5)
    at ocspResponseVerify (/app/node_modules/snowflake-sdk/lib/agent/check.js:201:7)
    at done (/app/node_modules/snowflake-sdk/lib/agent/check.js:71:7)
    at IncomingMessage.<anonymous> (/app/node_modules/snowflake-sdk/lib/agent/check.js:99:7)
    at IncomingMessage.emit (node:events:539:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by pavannarayan05** [comment]
> I have also just seen this today. We have not updated snowflake-sdk recently. We remain on 1.6.11.

Please do let me know if you find out something Mark. Would be of great help!

**Comment by markandrus** [comment]
In my case, a retry was sufficient, so I'm not sure what the root cause was.

**Comment by yakkomajuri** [comment]
We would also love to hear an update on this

**Comment by pavannarayan05** [comment]
I stopped getting this error after 3 weeks without any change made. Luckily, this was in Dev. I hope I don't see this in Production because I dont have a solution if this error occurs again. Any suggestions are welcome.

**Comment by yakkomajuri** [comment]
From my digging the SDK uses the filesystem to keep some sort of cache and it throws if it can't set the cache. This might be completely anecdotal but we have seen this at times of high CPU usage in our app, so I'm wondering if that plays a role. 

Nevertheless, given we're talking about a cache, is it possible to try-catch this as a temporary stopgap? This (seemingly) randomly crashes our server and I'd rather it didn't if the cache is not a core piece of functionality (I'd assume it isn't?)

cc @SimbaGithub @sfc-gh-kdama

**Comment by sfc-gh-dszmolka** [comment]
managed to reproduce the problem. at least for me, it comes when the
* local OCSP cache file is not present so the driver would need to download it from the remote cache (ocsp.snowflakecomputing.com)
* an artificial delay of 5s is introduced with `tc` on the interface which is used to internet-bound communications (thank you for the idea @yakkomajuri , hinting CPU usage might play a role)

will coordinate internally to see how best address this

**Comment by yakkomajuri** [comment]
great, thanks for looking into this!

**Comment by guillaume-chech** [comment]
I'm monitoring, any major update so far on that issue ?

**Comment by sfc-gh-dszmolka** [comment]
no update yet, thank you all for bearing with us. Will post if any important progress or the PR is available for the fix.

**Comment by sfc-gh-sfaber** [comment]
@sfc-gh-ext-simba-ti, the team is asking for an update on this ticket, I see it has been merged, is it fixed?

**Comment by sfc-gh-dszmolka** [comment]
hey folks quick update. the team is still working on the PR (see above), hopefully we can get it out soon. 
for those who are heavily impacted and need an immediate relief; you can try to [disable the OCSP checks](https://community.snowflake.com/s/article/How-to-turn-off-OCSP-checking-in-Snowflake-client-drivers) in the connector
(by adding `snowflake.configure({ insecureConnect: true });`)

of course this is **not recommended** on the long term, just putting it out here as a possible and temporal mitigation while the proper fix is underway. thank you for bearing with us !
