### ISSUE TITLE
BindUploader.Upload fails when one of the bind values is null

### ISSUE THREAD

**Issue by markddrake** [snowflakedb/snowflake-connector-nodejs#438]
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?

```
C:\Development\YADAMU\src\scratch\snowflake\bind>node --version
v18.9.0

C:\Development\YADAMU\src\scratch\snowflake\bind>npm --version
7.21.0

C:\Development\YADAMU\src\scratch\snowflake\bind>
```
2. What operating system and processor architecture are you using?
 ```
C:\Development\YADAMU\src\scratch\snowflake\bind> systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
```
3. What are the component versions in the environment (`npm list`)?
```
C:\Development\YADAMU\src\scratch\snowflake\bind>npm list
yadamu@1.0.0 C:\Development\YADAMU\src
+-- @azure/storage-blob@12.8.0
+-- @electron/remote@2.0.8
+-- aws-sdk@2.1267.0
+-- bootstrap-icons@1.10.2
+-- bootstrap@5.2.3
+-- cookie-parser@1.4.6
+-- csv-parser@3.0.0
+-- electron-packager@17.1.1
+-- electron@21.3.3
+-- express-session@1.17.3
+-- express@4.18.2
+-- font-awesome@4.7.0
+-- ibm_db_electron@npm:ibm_db@3.0.0
+-- ibm_db@3.1.0
+-- install@0.13.0
+-- jquery@3.6.1
+-- mariadb@2.5.6
+-- mime-types@2.1.35
+-- mongodb@3.7.3
+-- mssql@7.3.5
+-- mysql@2.18.1
+-- npm@8.19.3
+-- oracledb@5.5.0
+-- pg-copy-streams@2.2.2
+-- pg-query-stream@4.2.4
+-- pg@8.8.0
+-- readable-stream@3.6.0
+-- snowflake-sdk@1.6.19
+-- teradata-nodejs-driver@1.0.0-rc.15
+-- uuid@8.3.2
`-- wkx@0.5.0
```
4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```
import snowflake from 'snowflake-sdk';

import fs                 from "fs"

import { 
  performance 
}                         from 'perf_hooks';

import Parameters from 'snowflake-sdk/lib/parameters.js';

class Tester {

   constructor() {
    
	  this.connectionProperties =  {
  	    "account"                       : "UseYourOwn"
      , "username"                      : "UseYourOwn"
      , "password"                      : "UseYourOwn"
	  , "warehouse"                     : "DEMO_WH"
      , "database"                      : "DEMO_DB"
	  , "schema"                        : "PUBLIC"	  
    }
	
  }
   
  establishConnection(connection) {
      
    return new Promise((resolve,reject) => {
      connection.connect((err,connection) => {
        if (err) {
          reject(err)
        }
        resolve(connection)
      })
    })
  } 
  
  executeSQL(sqlStatement,binds) {
    
    return new Promise((resolve,reject) => {

	  this.connection.execute({
        sqlText        : sqlStatement
      , binds          : binds
	  , fetchAsString  : ['Number','Date','JSON']
      , complete       : async (err,statement,rows) => {
                           if (err) reject(err)
                           resolve(rows)
	                     }   
      })
    })
  }  
  
  async runTest() {

     const fileContent = JSON.parse(fs.readFileSync('dataset.json','utf-8'));
	 const ROWS = fileContent.length
	 const dataset = fileContent.flat().map((x) => { return ((x !== null) && (typeof x === 'object')) ? JSON.stringify(x) : x})
	 console.log(dataset.slice(0,20))
	 
     try {
       this.connection = snowflake.createConnection(this.connectionProperties)
       this.connection = await this.establishConnection(this.connection)
	   await this.executeSQL('CREATE TRANSIENT DATABASE IF NOT EXISTS \"TEST\" DATA_RETENTION_TIME_IN_DAYS = 0');
	   await this.executeSQL('USE DATABASE \"TEST\"');
	   await this.executeSQL('DROP SCHEMA IF EXISTS TEST');
	   await this.executeSQL('CREATE TRANSIENT SCHEMA TEST DATA_RETENTION_TIME_IN_DAYS=0');   	  
	   await this.executeSQL('CREATE TABLE "TEST"."TEST"(\"ID\" INT, \"TYPE\" VARCHAR(40), \"DATA\" VARIANT, \"CREATEDDATETIME\" TIMESTAMP_TZ(0) ,\"ACTION\" VARCHAR(256));');
	   const sql = `insert into \"TEST\".\"TEST\" (\"ID\",\"TYPE\",\"DATA\",\"CREATEDDATETIME\",\"ACTION\") select COLUMN1,COLUMN2,TRY_PARSE_JSON(COLUMN3),COLUMN4,COLUMN5 from values ${new Array(ROWS).fill('(?,?,?,?,?)').join(',')}`
	   const res1 = await this.executeSQL(sql,dataset);
	   console.log(res1)
	   dataset[4] = null;
	   const res2 = await this.executeSQL(sql,dataset);
	   console.log(res2)
	 } catch (e) {
	   console.log(e);
	 }
   }

}

async function main() {
  const t = new Tester()
  await t.runTest()
}

main().then(() => {console.log('Success')}).catch((e) => {console.log(e)})
```

5. What did you expect to see?

A successful insert

6. What did you see instead?
```
C:\Development\YADAMU\src\scratch\snowflake\bind>node test1.js
[
  '1',
  'SAMPLE',
  '{"user":{"SAP":"Not Available","email":"Not Available","pernr":"Not Available","lastname":"HKDL","firstname":"entboh1"},"username":"entboh1 HKDL","deviceName":null,"deviceType":"WEB","locationId":null,"clientIPAddress":"13.113.131.107"}',
  '2018-11-02T04:14:56.000000Z',
  null,
  '2',
  'SAMPLE',
  '{"type":"entitlementsCatalog","user":{"SAP":"Not Available","email":"Not Available","pernr":"Not Available","lastname":"HKDL","firstname":"entboh1"},"result":null,"success":"true","username":"entboh1 HKDL","deviceName":null,"deviceType":"WEB","entityType":"Report","locationId":null,"clientIPAddress":"13.113.131.107","supervisedUserUsername":null}',
  '2018-11-02T04:14:56.000000Z',
  null,
  '3',
  'SAMPLE',
  '{"type":"entitlementTransactions","user":{"SAP":"Not Available","email":"Not Available","pernr":"Not Available","lastname":"HKDL","firstname":"entboh1"},"result":null,"success":"true","username":"entboh1 HKDL","deviceName":null,"deviceType":"WEB","entityType":"Report","locationId":null,"clientIPAddress":"13.113.131.107","supervisedUserUsername":null}',
  '2018-11-02T04:14:56.000000Z',
  null,
  '4',
  'SAMPLE',
  '{"type":"usage","user":{"SAP":"Not Available","email":"Not Available","pernr":"Not Available","lastname":"HKDL","firstname":"entboh1"},"result":null,"success":"true","username":"entboh1 HKDL","deviceName":null,"deviceType":"WEB","entityType":"Report","locationId":null,"clientIPAddress":"13.113.131.107","supervisedUserUsername":null}',
  '2018-11-02T04:14:56.000000Z',
  null
]
Upload 28755
TypeError: Cannot read properties of null (reading 'length')
    at BindUploader.Upload (C:\Development\YADAMU\src\node_modules\snowflake-sdk\lib\connection\bind_uploader.js:70:32)
    at exports.createStatementPreExec (C:\Development\YADAMU\src\node_modules\snowflake-sdk\lib\connection\statement.js:100:25)
    at Connection.execute (C:\Development\YADAMU\src\node_modules\snowflake-sdk\lib\connection\connection.js:325:22)
    at file:///C:/Development/YADAMU/src/scratch/snowflake/bind/test1.js:43:20
    at new Promise (<anonymous>)
    at Tester.executeSQL (file:///C:/Development/YADAMU/src/scratch/snowflake/bind/test1.js:41:12)
    at Tester.runTest (file:///C:/Development/YADAMU/src/scratch/snowflake/bind/test1.js:71:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///C:/Development/YADAMU/src/scratch/snowflake/bind/test1.js:85:3)
Success

```
7. Add this to get standard output.
 
```
var snowflake = require('./snowflake');
snowflake.configure(
{
  logLevel: 'trace'
});
```

**Comment by markddrake** [comment]
[dataset.zip](https://github.com/snowflakedb/snowflake-connector-nodejs/files/10927723/dataset.zip)

**Comment by markddrake** [comment]
Note if also fails (differently) with non-null values..

Change the following line 
```
const dataset = fileContent.flat().map((x) => { return ((x !== null) && (typeof x === 'object')) ? JSON.stringify(x) : x})
``` 
to
```
const dataset = fileContent.flat().map((x) => { return (x == null) ? 'NULL' : (typeof x === 'object') ? JSON.stringify(x) : x})
```

and you get 
```
C:\Development\YADAMU\src\node_modules\snowflake-sdk\lib\connection\statement.js:148
                    throw err;
                    ^

Error [OperationFailedError]: SQL compilation error:
syntax error line 1 at position 25 unexpected 'D'.
parse error line 1 at position 33 near '65'.
parse error line 1 at position 41 near '76'.
parse error line 1 at position 47 near '84'.
parse error line 1 at position 52 near '116'.
parse error line 1 at position 62 near '49'.
syntax error line 1 at position 63 unexpected ''@SYSTEM$BIND/f63a393c-7dbb-44e6-93ca-435ca1411b85''.
    at createError (C:\Development\YADAMU\src\node_modules\snowflake-sdk\lib\errors.js:538:15)
    at exports.createOperationFailedError (C:\Development\YADAMU\src\node_modules\snowflake-sdk\lib\errors.js:317:10)
    at Object.callback (C:\Development\YADAMU\src\node_modules\snowflake-sdk\lib\services\sf.js:647:28)
    at C:\Development\YADAMU\src\node_modules\snowflake-sdk\lib\http\base.js:111:25
    at done (C:\Development\YADAMU\src\node_modules\urllib\lib\urllib.js:589:5)
    at C:\Development\YADAMU\src\node_modules\urllib\lib\urllib.js:953:9
    at decodeContent (C:\Development\YADAMU\src\node_modules\urllib\lib\urllib.js:740:14)
    at handleResponseCloseAndEnd (C:\Development\YADAMU\src\node_modules\urllib\lib\urllib.js:924:7)
    at IncomingMessage.<anonymous> (C:\Development\YADAMU\src\node_modules\urllib\lib\urllib.js:962:7)
    at IncomingMessage.emit (node:events:525:35) {
  code: '001003',
  sqlState: '42000',
  data: {
    internalError: false,
    errorCode: '001003',
    age: 0,
    sqlState: '42000',
    queryId: '01aad2c6-0402-a4c2-000d-5483013a6642',
    line: -1,
    pos: -1,
    type: 'COMPILATION'
  }
}
when you run the program
```

**Comment by markddrake** [comment]
Sorry for the large dataset. I could not find a way to force the code to use the BindLoader.Upload method with less complex data sets.

**Comment by markddrake** [comment]
Note both examples work as expected with snowflake-sdk@1.6.13

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you very much for submitting this issue and extra thanks for the detailed description! please don't be sorry for the big dataset; we appreciate it very much if someone can point out bugs in the library with such good details.

the error is indeed easily reproducible with your approach.
it seems calling `length()`  in  https://github.com/snowflakedb/snowflake-connector-nodejs/blob/v1.6.19/lib/connection/bind_uploader.js#L69 does not play very well with `null` values. passed it on to the team to take a look.

as with other `bind_uploader` related issues, besides using 1.6.13, the workaround is similar: bump `arrayBindingThreshold` to a larger value (option available in 1.6.17+) to avoid the whole `bind_uploader` code path and revert to the pre-1.6.14 behaviour. Example, using your repro:
```javascript
constructor() {

    this.connectionProperties = {
        "account": "UseYourOwn",
        "username": "UseYourOwn",
        "password": "UseYourOwn",
        "warehouse": "DEMO_WH",
        "database": "DEMO_DB",
        "schema": "PUBLIC",
        "arrayBindingThreshold": 500000 // default: 100000   
    }

}
```

For the
> Note if also fails (differently) with non-null values..

part, I could not reproduce this error:
```
Error [OperationFailedError]: SQL compilation error:
syntax error line 1 at position 25 unexpected 'D'.
parse error line 1 at position 33 near '65'.
parse error line 1 at position 41 near '76'.
parse error line 1 at position 47 near '84'.
parse error line 1 at position 52 near '116'.
parse error line 1 at position 62 near '49'.
syntax error line 1 at position 63 unexpected ''@SYSTEM$BIND/f63a393c-7dbb-44e6-93ca-435ca1411b85''.
```

When replacing `const dataset` definition with the new one and running the same script on the same dataset, i got `Bind variable ? not set.` error instead. I used only the first 10 items from your original dataset though for the reproductions here, maybe that plays a role here.

Anyways, for the parse error we have PR439 which fixed #420 for me at least in my tests, so let's hope it can work here too, once the new release is out which has PR439. (New releases usually come towards the end of the particular month, if there's changes to release)

**Comment by sfc-gh-dszmolka** [comment]
just realised this might be dupe of #373  (and, seems to be fixed by #443 )

**Comment by sfc-gh-dszmolka** [comment]
(closing this one as duplicate and keeping the original open until the PR is released in the new version of the driver)
