### ISSUE TITLE
Seeing a module load failure with recent update

### ISSUE THREAD

**Issue by artzte** [snowflakedb/snowflake-connector-nodejs#48]
I am seeing a dependency failure with the latest.
You are importing mkdirp but it is not part of the package.json dependencies.
````
Unable to import module 'index': Error
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/node_modules/snowflake-sdk/lib/global_config.js:10:16)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)

**Comment by notkriswagner** [comment]
Hi, when you say the latest are you talking about 1.2.0 (which was released a few hours ago)?

**Comment by artzte** [comment]
Yes. I performed a new build and the 1.2.0 was retrieved. But you can see the issue in your sources - https://github.com/snowflakedb/snowflake-connector-nodejs/search?q=mkdirp&unscoped_q=mkdirp - you are not importing mkdirp package. Perhaps it worked before, because one of your dependencies was importing it?

**Comment by notkriswagner** [comment]
Possibly, I'll add that to the package.json. Sorry we missed that

**Comment by notkriswagner** [comment]
@artzte A new version of NodeJS has been released (1.2.1) with the fixed package.json file. The broken release has also been removed to prevent other people from encountering this issue. Let me know if you still have any other problems.

**Comment by artzte** [comment]
Thanks, will check it out.

**Comment by artzte** [comment]
Hey @notkriswagner https://github.com/snowflakedb/snowflake-connector-nodejs/commit/5ddd0df706006658b548b21f64121003ecffd512 seems to be breaking us now. We are running in an AWS lambda with a read-only file system. So the new release does not work in our deployment environment. Is this new behavior?

````
2019-07-16T16:22:28.181Z	b98c1f38-46b0-42d4-b21b-3eb8fc3d9520	Error: EROFS: read-only file system, mkdir '/home/sbx_user1051'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/var/task/node_modules/mkdirp/index.js:71:13)
    at sync (/var/task/node_modules/mkdirp/index.js:77:24)
    at Function.sync (/var/task/node_modules/mkdirp/index.js:77:24)
    at Object.exports.mkdirCacheDir (/var/task/node_modules/snowflake-sdk/lib/global_config.js:127:20)
    at new OcspResponseCache (/var/task/node_modules/snowflake-sdk/lib/agent/ocsp_response_cache.js:46:33)
    at getOcspResponseCache (/var/task/node_modules/snowflake-sdk/lib/agent/socket_util.js:42:37)
    at getOcspResonseAndVerify (/var/task/node_modules/snowflake-sdk/lib/agent/socket_util.js:308:24)
    at validateCert (/var/task/node_modules/snowflake-sdk/lib/agent/socket_util.js:351:3)
    at eachCallback (/var/task/node_modules/snowflake-sdk/lib/agent/socket_util.js:217:5)

**Comment by notkriswagner** [comment]
That looks like the error is coming from the updated OCSP code, specifically the OCSP response cache. @smtakeda is there a way to disable the OCSP response cache or disable writing to disk?

**Comment by notkriswagner** [comment]
@artzte It looks like there is currently no way to shutoff the OCSP response cache. I've opened #50 to add an option to keep the OCSP response cache in memory to avoid this read-only disk issue.
