### ISSUE TITLE
SQL Binding for Limit Clause Errors Out

### ISSUE THREAD

**Issue by nirmalparekh1984** [snowflakedb/snowflake-connector-nodejs#65]
Snowflake-sdk for Nodejs version : "1.3.2"
Nodejs version v10.17.0

Trying to parameterize the row count in limit clause of SQL Query using Snowflake binding parameters but that does work and it return an error.
Note I have replaced actual query in the log below with a dummy query due to data sensitivity

```Successfully connected as id 599742ab-0b04-48c2-b21f-636255b38b77
SQL select column from schema.table limit ?
Bindings 20
{ OperationFailedError: SQL compilation error:
Invalid row count '?' in limit clause
    at createError (**/node_modules/snowflake-sdk/lib/errors.js:525:15)
    at Object.exports.createOperationFailedError (**/node_modules/snowflake-sdk/lib/errors.js:304:10)
    at Object.callback (**/node_modules/snowflake-sdk/lib/services/sf.js:624:28)
    at Request._callback (**/node_modules/snowflake-sdk/lib/http/base.js:107:19)
    at Request.self.callback (**/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (**/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (**/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'OperationFailedError',
  code: '002010',
  message:
   'SQL compilation error:\nInvalid row count \'?\' in limit clause',
  sqlState: '2201W',
  data:
   { internalError: false,
     errorCode: '002010',
     age: 0,
     sqlState: '2201W',
     queryId: '0190558c-0007-4a26-0000-10017b686507',
     line: -1,
     pos: -1,
     type: 'COMPILATION' } }
```

here is the code

**Query with Binding**
```
export const executeQuery = (): Promise<any> => {
    return new Promise((res, rej) => {
      const sql = 'select column from schema.table limit ?';
      const bindings = [20];
      querySnowflake(sql, bindings)
        .then(res)
        .catch(rej);
    });
};
```

**Connecting to Snowflake**
```
const connectSnowflake = async (
  env: string = process.env.NODE_ENV,
): Promise<SnowflakeConnection> => {
  // tslint:disable-next-line: max-line-length
  const environmentalConfiguration: SnowflakeInputs = environmentalConfigurations()[`snowflake_${env}`];
  return await new Promise((res: any, rej: any) => {
    snowflake.configure({ ocspFailOpen: false });
    const conn = snowflake.createConnection(environmentalConfiguration);
    if (conn) {
      conn.connect((err, conn) => {
        if (err) {
          rej(err);
        } else {
          console.log(`Successfully connected as id ${conn.getId()}`);
          res(conn);
        }
      });
    }
  });
};
```

**Executing Query**
```
export const querySnowflake = async (
  query: string, bindings: any[],
): Promise<SnowflakeResults> => {
  const conn: SnowflakeConnection = await connectSnowflake();
  console.log(`SQL ${query}`);
  console.log(`Bindings ${bindings}`);
  return await new Promise((res: any, rej: any) => {
    conn.execute({
      sqlText: query,
      binds: bindings,
      fetchAsString: ['Date'],

      complete: (err, _, rows) => {
        if (err) {
          rej(err);
        } else {
          console.log(rows);
          res(rows);
        }
      },
    });
  });
};
```

How do we ensure that even row count can be parameterized? 
It seems that there is bug in implementation in SDK where it is not identifying replacing the limit clause parameter.

**Comment by notkriswagner** [comment]
Hi @nirmalparekh1984 ,

The SDK does not actually do the replacement on the client side, we send the query and the bindings to the Snowflake service where the variables are bound. That looks like a limitation with server-side binding. Can you file a ticket with Snowflake support?

**Comment by nirmalparekh1984** [comment]
@notkriswagner  Thanks I have opened a ticket with Snowflake
