### ISSUE TITLE
SNOW-973185: `deno` runtime support

### ISSUE THREAD

**Issue by yassun7010** [snowflakedb/snowflake-connector-nodejs#701]
Hi ✋ 

I'm try to make AI Chatbot by using [Slack CLI](https://api.slack.com/automation/cli/install).

To make prompt text, we want to use Snowflake as data source, but we cannot call `snowflake-sdk` on deno runtime.

My sample code is here.

```typescript
import snowflake from "npm:snowflake-sdk@1.9.1";

let connection = snowflake.createConnection({
    account: "*************",
    username: "*************",
    password: "*************",
    database: '*************',
    warehouse: '*************',
    role: '*************',
});

connection.connect((err: any, conn: any) => {
    if (err) {
        console.error('Unable to connect: ' + err.message);
    } else {
        console.log('Successfully connected to Snowflake.');
      conn.execute({
        sqlText: 'SELECT 1',
        complete: (err: any, stmt: any, rows: any) => {
          for (const row of rows || []) {
            console.log(row);
          }
        }
      });
    }
});

```

and the following error occurs.

```
error: Uncaught TypeError: Class constructor Agent cannot be invoked without 'new'
    at HttpsOcspAgent (file:///Users/username/Library/Caches/deno/npm/registry.npmjs.org/snowflake-sdk/1.9.1/lib/agent/https_ocsp_agent.js:19:26)
    at createAgent (file:///Users/username/Library/Caches/deno/npm/registry.npmjs.org/snowflake-sdk/1.9.1/lib/http/node.js:53:19)
    at getFromCacheOrCreate (file:///Users/username/Library/Caches/deno/npm/registry.npmjs.org/snowflake-sdk/1.9.1/lib/http/node.js:63:13)
    at NodeHttpClient.getAgent (file:///Users/username/Library/Caches/deno/npm/registry.npmjs.org/snowflake-sdk/1.9.1/lib/http/node.js:115:15)
    at NodeHttpClient.prepareRequestOptions (file:///Users/username/Library/Caches/deno/npm/registry.npmjs.org/snowflake-sdk/1.9.1/lib/http/base.js:239:22)
    at NodeHttpClient.HttpClient.request (file:///Users/username/Library/Caches/deno/npm/registry.npmjs.org/snowflake-sdk/1.9.1/lib/http/base.js:39:48)
    at sendHttpRequest (file:///Users/username/Library/Caches/deno/npm/registry.npmjs.org/snowflake-sdk/1.9.1/lib/services/sf.js:722:23)
    at UnauthenticatedRequest.StateAbstract.Request.send (file:///Users/username/Library/Caches/deno/npm/registry.npmjs.org/snowflake-sdk/1.9.1/lib/services/sf.js:779:5)
    at sendRequest (file:///Users/username/Library/Caches/deno/npm/registry.npmjs.org/snowflake-sdk/1.9.1/lib/services/sf.js:1279:13)
    at StateConnecting.continue (file:///Users/username/Library/Caches/deno/npm/registry.npmjs.org/snowflake-sdk/1.9.1/lib/services/sf.js:1281:3)
```

This sample code can success on `Node.js` runtime.

Do you plan to support `deno` in the future?

I want it very much.

**Comment by sfc-gh-dszmolka** [comment]
hi there 👋  i don't see `deno` runtime support plans anywhere on the roadmap at this moment for the Snowflake Node.JS driver. of course if our customers/users require it, this might change at any time, but for the foreseeable future i don't see it planned. 

best way to proceed with this request (also putting it here for future readers) if you're already a Snowflake customer, please reach out to your account team and tell them how important the feature would be for you and they can help putting it on the roadmap and prioritize for the team.

since there's no plans whatsoever at the very moment of writing to support it, i'm marking this issue as closed.
