### ISSUE TITLE
SNOW-143538: We keep getting error 402001 - Network error. Could not reach S3/Blob.

### ISSUE THREAD

**Issue by Ginden** [snowflakedb/snowflake-connector-nodejs#85]
System:
Node v10.18.0
npm v6.13.4
Ubuntu 18.04.3 LTS
snowflake-sdk@1.3.1

**What did you do?**

We are running code like:
```
      this.snowflake.execute({
        sqlText,
        binds,
        streamResult: true,
        complete: done,
      })
```

Result set is around 500k rows.

5. What did you expect to see?
Working properly.

6. What did you see instead?

We are randomly seeing error:
```
 2020-03-09T10:50:44.794Z - error: Network error. Could not reach S3/Blob. NetworkError: Network error. Could not reach S3/Blob.
     at createError (/app/node_modules/snowflake-sdk/lib/errors.js:524:15)
     at Object.exports.createNetworkError (/app/node_modules/snowflake-sdk/lib/errors.js:249:10)
     at Object.callback (/app/node_modules/snowflake-sdk/lib/services/large_result_set.js:72:24)
     at Request._callback (/app/node_modules/snowflake-sdk/lib/http/base.js:107:19)
     at self.callback (/app/node_modules/request/request.js:185:22)
     at Request.emit (events.js:198:13)
     at Request.EventEmitter.emit (domain.js:448:20)
     at Timeout._onTimeout (/app/node_modules/request/request.js:852:16)
     at ontimeout (timers.js:436:11)
     at tryOnTimeout (timers.js:300:5)
```

Unfortunely, there isn't reliable way to trigger it.

How should we debug from this place?

**Comment by snowstakeda** [comment]
Added to the backlog.

**Comment by offero** [comment]
Just hit this too 
snowflake-sdk@1.5.2

**Comment by haggholm** [comment]
We are experiencing this problem with version 1.6.14 of the library, i.e. after the fix was implemented. Can you provide any more information about the root cause of the problem to better help us understand how to work around or address it?

**Comment by mikelecomte** [comment]
Seeing this intermittently with `1.6.23`, as of a couple days ago. Our process has been running fine for about 3 weeks prior to this.
